// histogram.comp
#version 450
layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba8) uniform image2D imgInput;
layout(std430, binding = 1) buffer Histogram {
    uint histo[];
};

#define HISTOGRAM256_BIN_COUNT 256

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    vec4 pixel = imageLoad(imgInput, coords);
    float Y = 0.299 * pixel.r + 0.587 * pixel.g + 0.114 * pixel.b;

    uint bin = uint(Y * 255.0);
    atomicAdd(histo[bin], 1);
}
